micronaut:
  application:
    name: accounts

  server:
    port: 80
    max-request-size: '100MB'
    cors:
      enabled: true
    multipart:
      max-file-size: '256MB'
    ssl:
      enabled: 'true'
    netty:
      worker:
        threads: 8
      childOptions:
        autoRead: true

  router:
    static-resources:
      public:
        enabled: true
        mapping: /**
        paths: classpath:public

  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://ldap.learn.berufskolleg-geilenkirchen.de'
          managerDn: 'cn=admin,dc=bkest,dc=schule'
          managerPassword: 'pHtSL4MhUlaTBaevsmka'
        search:
          base: "ou=Lehrer,dc=bkest,dc=schule"
          filter: "cn={0}"
        groups:
          enabled: true
          filter: "member={0}"
          base: "ou=System,dc=bkest,dc=schule"

    authentication: bearer
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

    endpoints:
      login:
        enabled: true
        path: '/auth/login'
      logout:
        enabled: true
        path: '/auth/logout'
      oauth:
        enabled: true
        path: '/auth/access_token'

    intercept-url-map:
      - pattern: /auth/**
        access:
          - isAnonymous()
      - pattern: /api/write/newpasswort
        http-method: POST
        access:
          - ROLE_TEACHER
      - pattern: /api/konfig/**
        http-method: GET
        access:
          - ROLE_ADMIN
      - pattern: /api/konfig/**
        http-method: POST
        access:
          - ROLE_ADMIN
      - pattern: /api/write/**
        http-method: GET
        access:
          - ROLE_ADMIN
      - pattern: /api/write/**
        http-method: POST
        access:
          - ROLE_ADMIN
      - pattern: /api/read/**
        http-method: GET
        access:
          - isAuthenticated()
      - pattern: /api/read/**
        http-method: POST
        access:
          - isAuthenticated()
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()

logger:
  levels:
    'name.hergeth': DEBUG
    'org.codehaus.jackson': INFO
    'io.micronaut': INFO
#    'io.micronaut.security': DEBUG
#    'io.micronaut.configuration.security.ldap': DEBUG

accounts:
  configpfad: 'config/accounts.json'

