micronaut:
  application:
    name: accounts
  server:
    ssl:
      enabled: 'true'
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
              
acme:
  enabled: 'true'
  tos-agree: 'true'
endpoints:
  info:
    enabled: true
    sensitive: false              




